require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'

target 'BlueshiftSampleApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )
    
  target 'BlueshiftSampleAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    targetsToFix = ["BlueShift-iOS-SDK-BlueShift-iOS-SDK_BlueShift_iOS_SDK"];
    installer.generated_projects.each do |project|
      project.targets.each do |target|
        if targetsToFix.include? target.name
          puts "Set development team for target #{target.name}"
          target.build_configurations.each do |config|
            config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
            config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
            config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
          end
        end
      end
    end
  end
end

target 'NotificationContent' do
  pod 'BlueShift-iOS-Extension-SDK'
end

target 'NotificationService' do
  pod 'BlueShift-iOS-Extension-SDK'
end

