require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/blueshift-react-native/process_install.rb'

platform :ios, '13.0'

target 'BlueshiftSampleApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )
    
  target 'BlueshiftSampleAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()
  
  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    blueshift_sdk_post_install(installer)
  end
end

target 'NotificationContent' do
  pod 'BlueShift-iOS-Extension-SDK'
end

target 'NotificationService' do
  pod 'BlueShift-iOS-Extension-SDK'
end

